<a href="https://colab.research.google.com/github/mahimalokre/Python_iiitb_code/blob/develop/PythonConcepts_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
# One of the reasons why NumPy arrays are efficient is because they are considered ‘C-contiguous’.
# Let’s ask a large language model what this means: Ask an LLM of your choice what it means for NumPy arrays to be C-contiguous.
import numpy as np

np.__version__

#!pip install numpy

'2.0.2'

In [ ]:
# 1. Homogeneous vs. Heterogeneous Data Types
# Python List: A Python list can contain elements of different types.
my_list = [1, 2.5, "hello", True]
print(my_list)  # [1, 2.5, 'hello', True]

# NumPy Array: NumPy tries to convert all elements to a single data type (here, string), so the array is homogeneous.
import numpy as np

my_array = np.array([1, 2.5, "hello", True])
print(my_array)  # ['1' '2.5' 'hello' 'True']
print(my_array.dtype)  # <U32 (string type)

[1, 2.5, 'hello', True]
['1' '2.5' 'hello' 'True']
<U32


In [43]:
# 2. Arrays of Varying Sizes
# Python List: You can have lists of different lengths inside a list.

list_of_lists = [[1, 2, 3], [4, 5], [6]]
print(list_of_lists)  # [[1, 2, 3], [4, 5], [6]]

# NumPy Array: NumPy cannot create a true multidimensional array with varying lengths; it falls back to dtype object,
# losing the benefits of fast computation.

array_of_arrays = np.array([[1, 2, 3], [4, 5], [6]])
print(array_of_arrays)
# Output: array([list([1, 2, 3]), list([4, 5]), list([6])], dtype=object)

[[1, 2, 3], [4, 5], [6]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [44]:
# 3. Optimized Mathematical Operations
# Python List:


list1 = [1, 2, 3]
list2 = [4, 5, 6]
# You can't do list1 + list2 for addition; it concatenates
print(list1 + list2)  # [1, 2, 3, 4, 5, 6]
# Element-wise addition requires a loop or comprehension
result = [x + y for x, y in zip(list1, list2)]
print(result)  # [5, 7, 9]

# NumPy Array: In NumPy, mathematical operations like addition, subtraction, multiplication, etc.
# ,are broadcasted element-wise without the need for loops.


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
# Element-wise addition
result = array1 + array2
print(result)  # [5 7 9]

[1, 2, 3, 4, 5, 6]
[5, 7, 9]
[5 7 9]


In [ ]:
# 4. Broadcasting: Broadcasting allows NumPy arrays of different shapes to be used together for arithmetic operations.
# Python List:

list1 = [1, 2, 3]
scalar = 2
# You cannot multiply a scalar directly element-wise; you need a loop or comprehension
result = [x * scalar for x in list1]
print(result)  # [2, 4, 6]

# NumPy Array: NumPy arrays are optimized for broadcasting, enabling operations between arrays and scalars or arrays of different shapes without explicit loops.

array = np.array([1, 2, 3])
scalar = 2
# Scalar multiplication is directly broadcasted
result = array * scalar
print(result)  # [2 4 6]


[2, 4, 6]
[2 4 6]


In [ ]:
# 5. Matrix Multiplication
# Python List:


list1 = [[1, 2], [3, 4]]
list2 = [[5, 6], [7, 8]]
# You need nested loops for matrix multiplication
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list2)] for row in list1]
print(result)  # [[19, 22], [43, 50]]

# NumPy Array: NumPy makes matrix multiplication simple and efficient using the @ operator or np.dot.


array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
# Matrix multiplication is straightforward using @ or np.dot
result = array1 @ array2  # Alternatively, np.dot(array1, array2)
print(result)  # [[19 22]
               #  [43 50]]

[[19, 22], [43, 50]]
[[19 22]
 [43 50]]


In [12]:
empty_array = np.array(object=[])
empty_array #O/p array([], dtype=float64)
type(empty_array) #O/p numpy.ndarray - data type of variable
empty_array.dtype #o/p dtype('float64') - data type of elements
empty_array.ndim #O/p 1 - Number of dimensions
empty_array.shape #O/p (0,) - Shape of the array
empty_array.size # O/p 0 - Size of the array; counts all elements accross dimension

0

In [15]:
#Numpy array with elements
array = np.array([1,1,3])
array.dtype

dtype('int64')

In [17]:
array = np.array(['Yes', 'no', 'numpy_array'])
type(array)
array.dtype

dtype('<U11')

In [19]:
array = np.array(range(1,10))
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array = np.arange(start=1, stop=15)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
array = np.arange(-10,2,3)
array

array([-10,  -7,  -4,  -1])

In [45]:
array = np.zeros(shape=10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros(shape = 10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.linspace(start = 2, stop = 3, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [49]:
np.linspace(2,3,7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [36]:
twoDArray = np.array([[1,2,3],[4,5,7]])
twoDArray.ndim

2

In [39]:
threeDArray = np.array([[[1,2,3], [3,4,5], [5,6,7]], [[1,8,9], [3,4,5], [5,6,7]]])
threeDArray

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 8, 9],
        [3, 4, 5],
        [5, 6, 7]]])

In [40]:
threeDArray.ndim

3